name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use system Python
        run: py -3.13.6 --version
        shell: powershell

      - name: Install dependencies
        run: |
          py -3.13.6 -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { py -3.10 -m pip install -r requirements.txt }
        shell: powershell

      - name: Lint
        run: |
          if (Get-Command flake8 -ErrorAction SilentlyContinue) { flake8 }
        shell: powershell

      - name: Run tests
        run: py -3.13.6 -m pytest -q
        shell: powershell
